title: All about Nursing Informatics
author: Jose P. Barbudo III, RN, MAN, ITIL, CPHIMS
email: jose.barbudo.phd@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This site aims to provide the most comprehensive content for Nursing Informatics.
Content includes history, evolution, definition, competencies & certification.
Contributors are definitely welcome to pull request and will be acknowledged.
Endorsement for external links are also considered for additional resources and reference.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
